-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Account CASCADE;
DROP TABLE IF EXISTS Task CASCADE;
DROP TABLE IF EXISTS PriorityScale CASCADE;
DROP TABLE IF EXISTS TaskClass CASCADE;